apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
  name: helm-api
  namespace: helm-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 8661
    protocol: TCP
    targetPort: 8661
  - name: grpc
    port: 8848
    protocol: TCP
    targetPort: 8848
  selector:
    app: helm-api
